config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  get 'home/about'

  get 'home/team'

  get 'home/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<HTML>
	<div class="content">
		<div class="contentbox">
			<h1>About</h1>

			<p>Bosham Capital Advisors (BCA) is an Independent Investment, Corporate Finance and Capital Advisory Firm which acts as an advisory bridge between Investors and Investees in Asia & UK.</p>
	 
			<p>BCA provides Investment, Corporate Finance, Strategic Advisory, M&A and Capital Raising services across the Digital Media, Disruptive Technology, Consumer and Real Estate sectors.</p>
		</div>
	</div>
</HTML>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<HTML>
  <body>
    <!-- Slideshow container -->
    <div class="slideshow-container" style='position:absolute;z-index:0;left:0;top:0;'>

      <!-- Full-width images with number and caption text -->
      <div class="mySlides fade">
        <img src="bg_home_1.2000x0.jpg" style="width:100%">
        <div class="picTitle">We Invest<br>We Advise<br>We Raise Capital</div>
        <div class="picText">+ Find out what we can do for you</div>
      </div>

      <div class="mySlides fade">
        <img src="bg_home_3.2000x0.jpg" style="width:100%">
        <div class="picTitle">Curated deals for Investors</div>
        <div class="picText">+ See our current deals</div>
      </div>

      <div class="mySlides fade">
        <img src="london.jpg" style="width:100%">
      </div>

    </div>
    <!-- The dots/circles -->
    <div class="scrollDots">
      <span class="dot" onclick="currentSlide(1)"></span> 
      <br>
      <span class="dot" onclick="currentSlide(2)"></span> 
      <br>
      <span class="dot" onclick="currentSlide(3)"></span> 
      <br>
    </div>
  </body>

</HTML>

<script type='text/javascript'>
  onload=currentSlide(1)
</script>

app/views/home/team.html.erb
<HTML>
	<div class="content">
		<h1>Home#team</h1>
		<p>Find me in app/views/home/team.html.erb</p>
		<p>test test test</p>
	</div>
</HTML>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bosham Capital Advisors</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
   	<div class="logo"><%= link_to image_tag("bca_logo_blue3.png"), root_path %></div>
   	<div onclick="myFunction()"" class="header3Drop"><%= "☰" %></div>
   	<div class="hidden" id="hidden">
   		<ul>
	   		<li><%= link_to "Home", root_path, :class => "headerButton" %></li>
	   		<li><%= link_to "About", home_about_path, :class => "headerButton" %></li>
	   		<li><%= link_to "Team", home_team_path, :class => "headerButton"  %></li>
	   		<li><%= link_to "Deals", home_team_path, :class => "headerButton"  %></li>
	   		<li><%= link_to "Portfolio", home_about_path, :class => "headerButton"  %></li>
	   		<li><%= link_to "Contact", home_team_path, :class => "headerButton"  %></li>
   		</div>
   	</div>
   	</ul>
  </header>
  <body>
    <%= yield %>
  </body>
</html>